### ISSUE TITLE
两个小疑问

### ISSUE THREAD

**Issue by AragakiChang** [Bedivere-Sun/write_react_project_from_scratch#1]
1. 在 .babelrc 中配置了 babel 后， webpack 中应该是不用再次配置的吧？
2. webpack-dev-server 貌似可以加上 --port 端口号 改变启动的端口？

**Comment by Bedivere-Sun** [comment]
1. 在`.babelrc`中配置了`babel`后，webpack 中应该是不用再次配置的吧？
是的，可以不用再配置。但是！`.babelrc`的优先级**高于**`webpack.config.js`的配置。

2. webpack-dev-server 貌似可以加上 --port 端口号 改变启动的端口？

可以，这是webpack-dev-server提供的一个命令行(又叫终端)参数。具体的webpack-dev-server都有哪些命令行参数……
我在Notes里面追加了`[webpack-dev-server终端命令说明书](https://github.com/Bedivere-Sun/write_react_project_from_scratch/blob/master/Notes/webpack-dev-server.md　"这篇应该是webpack-dev-server最全面的说明书了……Orz")`给你做参考。

看完之后是不是发现有很多好像都和webpack.config.js的配置出奇的相似？那就对了，因为这个模块就是模糊了前后端的边界的概念，在开发时既可以配置信息，又可以设置自动化脚本测试不同状况。

虽然这个项目没有对应的官方文档，不过我在一个贡献者的博客里发现居然在`webpack.config.js`中也是可以配置这个选项的(居然有这种操作)，配置的字段名叫`devServer`：
```javascript
//...
devServer{
  host: 'your_host',
  port: 22222
}
//...
```
这样即便不配置参数，直接运行`npx webpack-dev-server`也可以建立监听22222端口的服务。至于配置和命令行参数两者相较之下，命令行参数的优先级最大。如果你采用了上面的配置，之后运行`npx webpack-dev-server --port 9999`，它就会建立监听9999端口的服务了，里面22222的配置就被替换了。
